# Generated by Django 5.2.9 on 2025-12-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('food', 'Food & Beverages'), ('office', 'Office Supplies'), ('other', 'Other')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_warehouse', models.CharField(choices=[('main', 'Main Warehouse'), ('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], max_length=50)),
                ('to_warehouse', models.CharField(choices=[('main', 'Main Warehouse'), ('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('reconciled', 'Reconciled')], default='pending', max_length=20)),
                ('driver', models.CharField(blank=True, max_length=255, null=True)),
                ('mismatch_reason', models.TextField(blank=True, help_text='Reason for any quantity mismatch', null=True)),
                ('actual_quantity_received', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(choices=[('main', 'Main Warehouse'), ('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.product')),
            ],
            options={
                'ordering': ['warehouse', 'product'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
