# Generated by Django 5.2.9 on 2025-12-03 11:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Average Cost Price', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='valuation_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First-In, First-Out)'), ('lifo', 'LIFO (Last-In, First-Out)'), ('avco', 'Average Cost')], default='fifo', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling Price', max_digits=10),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(choices=[('main', 'Main Warehouse'), ('north', 'North Branch'), ('south', 'South Branch'), ('east', 'East Branch'), ('west', 'West Branch')], max_length=50)),
                ('quantity', models.IntegerField(help_text='Negative for removal, Positive for addition')),
                ('reason', models.CharField(choices=[('damage', 'Damaged Stock'), ('theft', 'Theft/Loss'), ('correction', 'Inventory Correction'), ('return', 'Customer Return')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Initial quantity received')),
                ('remaining_quantity', models.IntegerField(help_text='Current quantity remaining in this batch')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['received_date', 'created_at'],
            },
        ),
    ]
